//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPadrao.Dados.DAO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using ProjetoPadrao.Dados.Entidades;
    
    public static partial class ArquivoDAO
    {
    	public static IQueryable<Arquivo> Listar()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.Arquivos.AsNoTracking();
    	}
    
    	public static IQueryable<Arquivo> ListarTracking()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.Arquivos;
    	}
    
    	public static Arquivo BuscarPorChave(params object[] valoresChave)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.Arquivos.Find(valoresChave);
    	}
    
    	public static void Inserir(Arquivo arquivo, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.Arquivos.Add(arquivo);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void InserirColecao(IEnumerable<Arquivo> arquivos, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.Arquivos.AddRange(arquivos);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void Excluir(Arquivo arquivo, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.Arquivos.Remove(arquivo);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void SalvarAlteracoesPendentes()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.SaveChanges();
    	}
    }
}
