//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPadrao.Dados.DAO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using ProjetoPadrao.Dados.Entidades;
    
    public static partial class ConteudoDAO
    {
    	public static IQueryable<Conteudo> Listar()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.Conteudos.AsNoTracking();
    	}
    
    	public static IQueryable<Conteudo> ListarTracking()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.Conteudos;
    	}
    
    	public static Conteudo BuscarPorChave(params object[] valoresChave)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.Conteudos.Find(valoresChave);
    	}
    
    	public static void Inserir(Conteudo conteudo, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.Conteudos.Add(conteudo);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void InserirColecao(IEnumerable<Conteudo> conteudos, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.Conteudos.AddRange(conteudos);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void Excluir(Conteudo conteudo, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.Conteudos.Remove(conteudo);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void SalvarAlteracoesPendentes()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.SaveChanges();
    	}
    }
}
