//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPadrao.Dados.DAO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using ProjetoPadrao.Dados.Entidades;
    
    public static partial class GaleriaConteudoDAO
    {
    	public static IQueryable<GaleriaConteudo> Listar()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.GaleriasConteudos.AsNoTracking();
    	}
    
    	public static IQueryable<GaleriaConteudo> ListarTracking()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.GaleriasConteudos;
    	}
    
    	public static GaleriaConteudo BuscarPorChave(params object[] valoresChave)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.GaleriasConteudos.Find(valoresChave);
    	}
    
    	public static void Inserir(GaleriaConteudo galeriaconteudo, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.GaleriasConteudos.Add(galeriaconteudo);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void InserirColecao(IEnumerable<GaleriaConteudo> galeriasconteudos, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.GaleriasConteudos.AddRange(galeriasconteudos);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void Excluir(GaleriaConteudo galeriaconteudo, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.GaleriasConteudos.Remove(galeriaconteudo);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void SalvarAlteracoesPendentes()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.SaveChanges();
    	}
    }
}
