//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPadrao.Dados.DAO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using ProjetoPadrao.Dados.Entidades;
    
    public static partial class IdiomaDAO
    {
    	public static IQueryable<Idioma> Listar()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.Idiomas.AsNoTracking();
    	}
    
    	public static IQueryable<Idioma> ListarTracking()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.Idiomas;
    	}
    
    	public static Idioma BuscarPorChave(params object[] valoresChave)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.Idiomas.Find(valoresChave);
    	}
    
    	public static void Inserir(Idioma idioma, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.Idiomas.Add(idioma);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void InserirColecao(IEnumerable<Idioma> idiomas, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.Idiomas.AddRange(idiomas);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void Excluir(Idioma idioma, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.Idiomas.Remove(idioma);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void SalvarAlteracoesPendentes()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.SaveChanges();
    	}
    }
}
