//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPadrao.Dados.DAO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using ProjetoPadrao.Dados.Entidades;
    
    public static partial class TemplateDAO
    {
    	public static IQueryable<Template> Listar()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.Templates.AsNoTracking();
    	}
    
    	public static IQueryable<Template> ListarTracking()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.Templates;
    	}
    
    	public static Template BuscarPorChave(params object[] valoresChave)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		return bancoDados.Templates.Find(valoresChave);
    	}
    
    	public static void Inserir(Template template, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.Templates.Add(template);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void InserirColecao(IEnumerable<Template> templates, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.Templates.AddRange(templates);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void Excluir(Template template, bool salvarAlteracoes = true)
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.Templates.Remove(template);
    
    		if (salvarAlteracoes)
    		{
    			bancoDados.SaveChanges();
    		}
    	}
    
    	public static void SalvarAlteracoesPendentes()
    	{
    		var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;
    
    		bancoDados.SaveChanges();
    	}
    }
}
