//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPadrao.Dados.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arquivo
    {
        public int IdArquivo { get; set; }
        public string Nome { get; set; }
        public string NomeOriginal { get; set; }
        public string Extensao { get; set; }
        public long Tamanho { get; set; }
        public string Descricao { get; set; }
        public string TipoArquivo { get; set; }
    }
}
