//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPadrao.Dados.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categoria()
        {
            this.Subcategorias = new HashSet<Categoria>();
        }
    
        public int IdCategoria { get; set; }
        public string Nome { get; set; }
        public string URL { get; set; }
        public string HTML { get; set; }
        public bool Ativa { get; set; }
        public Nullable<int> IdCategoriaPai { get; set; }
        public int IdTemplate { get; set; }
        public int IdGrupoIdioma { get; set; }
        public int IdIdioma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categoria> Subcategorias { get; set; }
        public virtual Categoria CategoriaPai { get; set; }
        public virtual GrupoIdioma GrupoIdioma { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual Template Template { get; set; }
    }
}
