//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPadrao.Dados.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conteudo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conteudo()
        {
            this.GaleriasConteudo = new HashSet<GaleriaConteudo>();
        }
    
        public int IdConteudo { get; set; }
        public string Titulo { get; set; }
        public string URL { get; set; }
        public string Chamada { get; set; }
        public string HTML { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<System.DateTime> DataModificacao { get; set; }
        public Nullable<System.DateTime> DataPublicacao { get; set; }
        public bool Ativo { get; set; }
        public int IdCategoria { get; set; }
        public int IdTemplate { get; set; }
        public Nullable<int> IdArquivoImagemChamada { get; set; }
        public int IdGrupoIdioma { get; set; }
        public int IdIdioma { get; set; }
    
        public virtual GrupoIdioma GrupoIdioma { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual Imagem ImagemChamada { get; set; }
        public virtual Template Template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GaleriaConteudo> GaleriasConteudo { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
