//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPadrao.Dados.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MidiaGaleria
    {
        public int IdArquivo { get; set; }
        public int IdGaleria { get; set; }
        public int Ordem { get; set; }
    
        public virtual Galeria Galeria { get; set; }
        public virtual Midia Midia { get; set; }
    }
}
