//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPadrao.Dados.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetoPadrao : DbContext
    {
        public ProjetoPadrao()
            : base("name=ProjetoPadrao")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arquivo> Arquivos { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Conteudo> Conteudos { get; set; }
        public virtual DbSet<Galeria> Galerias { get; set; }
        public virtual DbSet<GaleriaConteudo> GaleriasConteudos { get; set; }
        public virtual DbSet<GrupoIdioma> GruposIdiomas { get; set; }
        public virtual DbSet<Idioma> Idiomas { get; set; }
        public virtual DbSet<MidiaGaleria> MidiasGalerias { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
    }
}
