//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPadrao.Dados.DAO
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using ProjetoPadrao.Dados.Entidades;

    public static partial class TemplateDAO
    {
        public static Template BuscarPorAlias(string alias)
        {
            var bancoDados = DbContextFactory<ProjetoPadrao>.Instance;

            return bancoDados.Templates.FirstOrDefault(t => t.Alias == alias);
        }
    }
}
