/*
Deployment script for ProjetoPadrao

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
USE [ProjetoPadrao];


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[Id] (SqlSimpleColumn) will not be renamed to IdIdioma';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[Id] (SqlSimpleColumn) will not be renamed to IdGrupoIdioma';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[Id] (SqlSimpleColumn) will not be renamed to IdArquivo';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[Id] (SqlSimpleColumn) will not be renamed to IdArquivo';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[Id] (SqlSimpleColumn) will not be renamed to IdArquivo';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[Id] (SqlSimpleColumn) will not be renamed to IdArquivo';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[Id] (SqlSimpleColumn) will not be renamed to IdTemplate';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Imagem].[Id] (SqlSimpleColumn) will not be renamed to IdArquivo';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[Id] (SqlSimpleColumn) will not be renamed to IdCategoria';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Categoria].[IX_Categoria_Column] (SqlIndex) will not be renamed to IX_Categoria_IdGrupoIdioma_IdIdioma';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Categoria].[IdGrupoIdioma] (SqlSimpleColumn) will not be renamed to IdCategoriaPai';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Conteudo].[Id] (SqlSimpleColumn) will not be renamed to IdConteudo';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Galeria].[Id] (SqlSimpleColumn) will not be renamed to IdGaleria';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[GaleriaConteudo].[Id] (SqlSimpleColumn) will not be renamed to IdGaleria';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[ArquivoGaleria].[Id] (SqlSimpleColumn) will not be renamed to IdArquivo';


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[Arquivo]...';


GO
CREATE TABLE [dbo].[Arquivo] (
    [IdArquivo]    INT            IDENTITY (1, 1) NOT NULL,
    [Nome]         NVARCHAR (255) NOT NULL,
    [NomeOriginal] NVARCHAR (255) NOT NULL,
    [Extensao]     NVARCHAR (10)  NOT NULL,
    [Tamanho]      BIGINT         NOT NULL,
    [Descricao]    NTEXT          NULL,
    [TipoArquivo]  NVARCHAR (10)  NOT NULL,
    CONSTRAINT [PK_Arquivo] PRIMARY KEY CLUSTERED ([IdArquivo] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Audio]...';


GO
CREATE TABLE [dbo].[Audio] (
    [IdArquivo] INT      NOT NULL,
    [Duracao]   TIME (7) NOT NULL,
    CONSTRAINT [PK_Audio] PRIMARY KEY CLUSTERED ([IdArquivo] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Categoria]...';


GO
CREATE TABLE [dbo].[Categoria] (
    [IdCategoria]    INT            IDENTITY (1, 1) NOT NULL,
    [Nome]           NVARCHAR (500) NOT NULL,
    [URL]            NVARCHAR (500) NOT NULL,
    [HTML]           NTEXT          NULL,
	[Ativa]          BIT            NOT NULL,
	[Ordem]          INT            NOT NULL,
    [IdCategoriaPai] INT            NULL,
    [IdTemplate]     INT            NOT NULL,
    [IdGrupoIdioma]  INT            NOT NULL,
    [IdIdioma]       INT            NOT NULL,
    CONSTRAINT [PK_Categoria] PRIMARY KEY CLUSTERED ([IdCategoria] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Categoria].[IX_Categoria_IdGrupoIdioma_IdIdioma]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Categoria_IdGrupoIdioma_IdIdioma]
    ON [dbo].[Categoria]([IdGrupoIdioma] ASC, [IdIdioma] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Conteudo]...';


GO
CREATE TABLE [dbo].[Conteudo] (
    [IdConteudo]             INT            IDENTITY (1, 1) NOT NULL,
    [Titulo]                 NVARCHAR (500) NOT NULL,
    [URL]                    NVARCHAR (500) NOT NULL,
    [Chamada]                NVARCHAR (500) NULL,
    [HTML]                   NTEXT          NOT NULL,
	[DataCriacao]            DATETIME       NOT NULL DEFAULT GETDATE(),
	[DataModificacao]        DATETIME       NULL,
	[DataPublicacao]         DATETIME       NULL,
	[Ativo]                  BIT            NOT NULL,
    [IdCategoria]            INT            NOT NULL,
    [IdTemplate]             INT            NOT NULL,
    [IdArquivoImagemChamada] INT            NULL,
    [IdGrupoIdioma]          INT            NOT NULL,
    [IdIdioma]               INT            NOT NULL,
    CONSTRAINT [PK_Conteudo] PRIMARY KEY CLUSTERED ([IdConteudo] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Categoria].[IX_Conteudo_IdGrupoIdioma_IdIdioma]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Conteudo_IdGrupoIdioma_IdIdioma]
    ON [dbo].[Categoria]([IdGrupoIdioma] ASC, [IdIdioma] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Documento]...';


GO
CREATE TABLE [dbo].[Documento] (
    [IdArquivo]     INT           NOT NULL,
    [TipoDocumento] NVARCHAR (10) NOT NULL,
    CONSTRAINT [PK_Documento] PRIMARY KEY CLUSTERED ([IdArquivo] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Galeria]...';


GO
CREATE TABLE [dbo].[Galeria] (
    [IdGaleria] INT            IDENTITY (1, 1) NOT NULL,
    [Nome]      NVARCHAR (500) NULL,
    [Descricao] NTEXT          NULL,
    CONSTRAINT [PK_Galeria] PRIMARY KEY CLUSTERED ([IdGaleria] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[GaleriaConteudo]...';


GO
CREATE TABLE [dbo].[GaleriaConteudo] (
    [IdGaleria]  INT NOT NULL,
    [IdConteudo] INT NOT NULL,
    [Ordem]      INT NOT NULL,
    CONSTRAINT [PK_GaleriaConteudo] PRIMARY KEY CLUSTERED ([IdGaleria] ASC, [IdConteudo] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[GrupoIdioma]...';


GO
CREATE TABLE [dbo].[GrupoIdioma] (
    [IdGrupoIdioma]   INT           IDENTITY (1, 1) NOT NULL,
    [TipoGrupoIdioma] NVARCHAR (10) NOT NULL,
    CONSTRAINT [PK_GrupoIdioma] PRIMARY KEY CLUSTERED ([IdGrupoIdioma] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Idioma]...';


GO
CREATE TABLE [dbo].[Idioma] (
    [IdIdioma] INT           IDENTITY (1, 1) NOT NULL,
    [Nome]     NVARCHAR (50) NOT NULL,
    [Sigla]    NVARCHAR (10) NOT NULL,
    CONSTRAINT [PK_Idioma] PRIMARY KEY CLUSTERED ([IdIdioma] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Imagem]...';


GO
CREATE TABLE [dbo].[Imagem] (
    [IdArquivo] INT NOT NULL,
    [Largura]   INT NOT NULL,
    [Altura]    INT NOT NULL,
    CONSTRAINT [PK_Imagem] PRIMARY KEY CLUSTERED ([IdArquivo] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Midia]...';


GO
CREATE TABLE [dbo].[Midia] (
    [IdArquivo] INT           NOT NULL,
    [TipoMidia] NVARCHAR (10) NOT NULL,
    CONSTRAINT [PK_Midia] PRIMARY KEY CLUSTERED ([IdArquivo] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[MidiaGaleria]...';


GO
CREATE TABLE [dbo].[MidiaGaleria] (
    [IdArquivo] INT NOT NULL,
    [IdGaleria] INT NOT NULL,
    [Ordem]     INT NOT NULL,
    CONSTRAINT [PK_MidiaGaleria] PRIMARY KEY CLUSTERED ([IdArquivo] ASC, [IdGaleria] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Template]...';


GO
CREATE TABLE [dbo].[Template] (
    [IdTemplate]               INT            IDENTITY (1, 1) NOT NULL,
    [Nome]                     NVARCHAR (500) NOT NULL,
    [Alias]                    NVARCHAR (500) NOT NULL,
    [HTML]                     NTEXT          NOT NULL,
    [ParseHTML]                BIT            NOT NULL,
    [IdArquivoImagemMiniatura] INT            NULL,
    CONSTRAINT [PK_Template] PRIMARY KEY CLUSTERED ([IdTemplate] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[Video]...';


GO
CREATE TABLE [dbo].[Video] (
    [IdArquivo] INT      NOT NULL,
    [Largura]   INT      NOT NULL,
    [Altura]    INT      NOT NULL,
    [Duracao]   TIME (7) NOT NULL,
    CONSTRAINT [PK_Video] PRIMARY KEY CLUSTERED ([IdArquivo] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Audio_Midia]...';


GO
ALTER TABLE [dbo].[Audio] WITH NOCHECK
    ADD CONSTRAINT [FK_Audio_Midia] FOREIGN KEY ([IdArquivo]) REFERENCES [dbo].[Midia] ([IdArquivo]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Categoria_Categoria]...';


GO
ALTER TABLE [dbo].[Categoria] WITH NOCHECK
    ADD CONSTRAINT [FK_Categoria_Categoria] FOREIGN KEY ([IdCategoriaPai]) REFERENCES [dbo].[Categoria] ([IdCategoria]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Categoria_Template]...';


GO
ALTER TABLE [dbo].[Categoria] WITH NOCHECK
    ADD CONSTRAINT [FK_Categoria_Template] FOREIGN KEY ([IdTemplate]) REFERENCES [dbo].[Template] ([IdTemplate]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Categoria_GrupoIdioma]...';


GO
ALTER TABLE [dbo].[Categoria] WITH NOCHECK
    ADD CONSTRAINT [FK_Categoria_GrupoIdioma] FOREIGN KEY ([IdGrupoIdioma]) REFERENCES [dbo].[GrupoIdioma] ([IdGrupoIdioma]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Categoria_Idioma]...';


GO
ALTER TABLE [dbo].[Categoria] WITH NOCHECK
    ADD CONSTRAINT [FK_Categoria_Idioma] FOREIGN KEY ([IdIdioma]) REFERENCES [dbo].[Idioma] ([IdIdioma]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Conteudo_Categoria]...';


GO
ALTER TABLE [dbo].[Conteudo] WITH NOCHECK
    ADD CONSTRAINT [FK_Conteudo_Categoria] FOREIGN KEY ([IdCategoria]) REFERENCES [dbo].[Categoria] ([IdCategoria]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Conteudo_Template]...';


GO
ALTER TABLE [dbo].[Conteudo] WITH NOCHECK
    ADD CONSTRAINT [FK_Conteudo_Template] FOREIGN KEY ([IdTemplate]) REFERENCES [dbo].[Template] ([IdTemplate]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Conteudo_Imagem]...';


GO
ALTER TABLE [dbo].[Conteudo] WITH NOCHECK
    ADD CONSTRAINT [FK_Conteudo_Imagem] FOREIGN KEY ([IdArquivoImagemChamada]) REFERENCES [dbo].[Imagem] ([IdArquivo]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Conteudo_GrupoIdioma]...';


GO
ALTER TABLE [dbo].[Conteudo] WITH NOCHECK
    ADD CONSTRAINT [FK_Conteudo_GrupoIdioma] FOREIGN KEY ([IdGrupoIdioma]) REFERENCES [dbo].[GrupoIdioma] ([IdGrupoIdioma]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Conteudo_Idioma]...';


GO
ALTER TABLE [dbo].[Conteudo] WITH NOCHECK
    ADD CONSTRAINT [FK_Conteudo_Idioma] FOREIGN KEY ([IdIdioma]) REFERENCES [dbo].[Idioma] ([IdIdioma]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Documento_Arquivo]...';


GO
ALTER TABLE [dbo].[Documento] WITH NOCHECK
    ADD CONSTRAINT [FK_Documento_Arquivo] FOREIGN KEY ([IdArquivo]) REFERENCES [dbo].[Arquivo] ([IdArquivo]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_GaleriaConteudo_Galeria]...';


GO
ALTER TABLE [dbo].[GaleriaConteudo] WITH NOCHECK
    ADD CONSTRAINT [FK_GaleriaConteudo_Galeria] FOREIGN KEY ([IdGaleria]) REFERENCES [dbo].[Galeria] ([IdGaleria]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_GaleriaConteudo_Conteudo]...';


GO
ALTER TABLE [dbo].[GaleriaConteudo] WITH NOCHECK
    ADD CONSTRAINT [FK_GaleriaConteudo_Conteudo] FOREIGN KEY ([IdConteudo]) REFERENCES [dbo].[Conteudo] ([IdConteudo]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Imagem_Midia]...';


GO
ALTER TABLE [dbo].[Imagem] WITH NOCHECK
    ADD CONSTRAINT [FK_Imagem_Midia] FOREIGN KEY ([IdArquivo]) REFERENCES [dbo].[Midia] ([IdArquivo]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Midia_Arquivo]...';


GO
ALTER TABLE [dbo].[Midia] WITH NOCHECK
    ADD CONSTRAINT [FK_Midia_Arquivo] FOREIGN KEY ([IdArquivo]) REFERENCES [dbo].[Arquivo] ([IdArquivo]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_MidiaGaleria_Midia]...';


GO
ALTER TABLE [dbo].[MidiaGaleria] WITH NOCHECK
    ADD CONSTRAINT [FK_MidiaGaleria_Midia] FOREIGN KEY ([IdArquivo]) REFERENCES [dbo].[Midia] ([IdArquivo]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_MidiaGaleria_Galeria]...';


GO
ALTER TABLE [dbo].[MidiaGaleria] WITH NOCHECK
    ADD CONSTRAINT [FK_MidiaGaleria_Galeria] FOREIGN KEY ([IdGaleria]) REFERENCES [dbo].[Galeria] ([IdGaleria]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Template_Imagem]...';


GO
ALTER TABLE [dbo].[Template] WITH NOCHECK
    ADD CONSTRAINT [FK_Template_Imagem] FOREIGN KEY ([IdArquivoImagemMiniatura]) REFERENCES [dbo].[Imagem] ([IdArquivo]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Video_Midia]...';


GO
ALTER TABLE [dbo].[Video] WITH NOCHECK
    ADD CONSTRAINT [FK_Video_Midia] FOREIGN KEY ([IdArquivo]) REFERENCES [dbo].[Midia] ([IdArquivo]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [ProjetoPadrao];


GO
ALTER TABLE [dbo].[Audio] WITH CHECK CHECK CONSTRAINT [FK_Audio_Midia];

ALTER TABLE [dbo].[Categoria] WITH CHECK CHECK CONSTRAINT [FK_Categoria_Categoria];

ALTER TABLE [dbo].[Categoria] WITH CHECK CHECK CONSTRAINT [FK_Categoria_Template];

ALTER TABLE [dbo].[Categoria] WITH CHECK CHECK CONSTRAINT [FK_Categoria_GrupoIdioma];

ALTER TABLE [dbo].[Categoria] WITH CHECK CHECK CONSTRAINT [FK_Categoria_Idioma];

ALTER TABLE [dbo].[Conteudo] WITH CHECK CHECK CONSTRAINT [FK_Conteudo_Categoria];

ALTER TABLE [dbo].[Conteudo] WITH CHECK CHECK CONSTRAINT [FK_Conteudo_Template];

ALTER TABLE [dbo].[Conteudo] WITH CHECK CHECK CONSTRAINT [FK_Conteudo_Imagem];

ALTER TABLE [dbo].[Conteudo] WITH CHECK CHECK CONSTRAINT [FK_Conteudo_GrupoIdioma];

ALTER TABLE [dbo].[Conteudo] WITH CHECK CHECK CONSTRAINT [FK_Conteudo_Idioma];

ALTER TABLE [dbo].[Documento] WITH CHECK CHECK CONSTRAINT [FK_Documento_Arquivo];

ALTER TABLE [dbo].[GaleriaConteudo] WITH CHECK CHECK CONSTRAINT [FK_GaleriaConteudo_Galeria];

ALTER TABLE [dbo].[GaleriaConteudo] WITH CHECK CHECK CONSTRAINT [FK_GaleriaConteudo_Conteudo];

ALTER TABLE [dbo].[Imagem] WITH CHECK CHECK CONSTRAINT [FK_Imagem_Midia];

ALTER TABLE [dbo].[Midia] WITH CHECK CHECK CONSTRAINT [FK_Midia_Arquivo];

ALTER TABLE [dbo].[MidiaGaleria] WITH CHECK CHECK CONSTRAINT [FK_MidiaGaleria_Midia];

ALTER TABLE [dbo].[MidiaGaleria] WITH CHECK CHECK CONSTRAINT [FK_MidiaGaleria_Galeria];

ALTER TABLE [dbo].[Template] WITH CHECK CHECK CONSTRAINT [FK_Template_Imagem];

ALTER TABLE [dbo].[Video] WITH CHECK CHECK CONSTRAINT [FK_Video_Midia];


GO
PRINT N'Update complete.';


GO
